# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('homepage', models.URLField()),
                ('feed', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('about', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('person', models.CharField(blank=True, max_length=255, verbose_name='Name of responsible contact')),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('is_producer', models.BooleanField(default=True, help_text='Is this a producer (and not only distributor)?', verbose_name='Producer')),
                ('datasource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='openfarms.Datasource')),
                ('distributors', models.ManyToManyField(blank=True, related_name='_farm_distributors_+', to='openfarms.Farm')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True)),
                ('imageurl', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': 'Produce',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('imageurl', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='labels',
            field=models.ManyToManyField(blank=True, to='openfarms.Label'),
        ),
        migrations.AddField(
            model_name='farm',
            name='produce',
            field=models.ManyToManyField(blank=True, related_name='farms', to='openfarms.Produce'),
        ),
        migrations.AddField(
            model_name='farm',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='openfarms.Region'),
        ),
    ]
