# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleindexpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='articleindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='articlerelatedlink',
            name='page',
        ),
        migrations.DeleteModel(
            name='ArticleIndexPage',
        ),
        migrations.DeleteModel(
            name='ArticlePage',
        ),
        migrations.DeleteModel(
            name='ArticleRelatedLink',
        ),
    ]
