# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:50
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_articleindexpage_articlepage_articlerelatedlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='postdate',
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default=''),
        ),
    ]
