# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture_url', models.URLField(blank=True)),
                ('translate_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type_of_dish_quantity', models.CharField(blank=True, choices=[('Gericht', 'Gericht'), ('Suppe', 'Suppe'), ('Dessert', 'Dessert')], max_length=20, null=True, verbose_name='Art der Teller')),
                ('Ingredient', wagtail.wagtailcore.fields.StreamField((('zutaten', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.ingredient')),))),
                ('steps', wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.TextBlock()),))),
                ('is_spicy', models.BooleanField(default=False, verbose_name='Scharf')),
                ('is_vegi', models.BooleanField(default=False, verbose_name='Vegi')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[('2017', 2017)], null=True, verbose_name='Jahr')),
                ('week', models.SmallIntegerField(choices=[('01', 1), ('02', 2), ('03', 3), ('04', 4), ('05', 5), ('06', 6), ('07', 7), ('08', 8), ('09', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18), ('19', 19), ('20', 20), ('21', 21), ('22', 22), ('23', 23), ('24', 24), ('25', 25), ('26', 26), ('27', 27), ('28', 28), ('29', 29), ('30', 30), ('31', 31), ('32', 32), ('33', 33), ('34', 34), ('35', 35), ('36', 36), ('37', 37), ('38', 38), ('39', 39), ('40', 40), ('41', 41), ('42', 42), ('43', 43), ('44', 44), ('45', 45), ('46', 46), ('47', 47), ('48', 48), ('49', 49), ('50', 50), ('51', 51), ('52', 52), ('53', 53)], null=True, verbose_name='Woche')),
                ('dishes_sp', wagtail.wagtailcore.fields.StreamField((('menu', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.menu')),), null=True)),
                ('dishes_1', wagtail.wagtailcore.fields.StreamField((('menu', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.menu')),), null=True)),
                ('dishes_2', wagtail.wagtailcore.fields.StreamField((('menu', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.menu')),), null=True)),
                ('dishes_3', wagtail.wagtailcore.fields.StreamField((('menu', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.menu')),), null=True)),
                ('dishes_4', wagtail.wagtailcore.fields.StreamField((('menu', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.menu')),), null=True)),
                ('dishes_5', wagtail.wagtailcore.fields.StreamField((('menu', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.menu')),), null=True)),
            ],
        ),
    ]
