# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture_url', models.URLField(blank=True)),
                ('translate_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('type_of_dish_quantity', models.CharField(blank=True, choices=[('Gericht', 'Gericht'), ('Suppe', 'Suppe'), ('Dessert', 'Dessert')], max_length=20, null=True, verbose_name='Art der Teller')),
                ('Ingredient', wagtail.wagtailcore.fields.StreamField((('zutaten', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.ingredient')),), blank=True, null=True, verbose_name='')),
                ('zutaten_beschreibung', models.TextField(blank=True, verbose_name='Zutaten Beschreibung')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='Scharf')),
                ('is_vegi', models.BooleanField(default=False, verbose_name='Vegi')),
                ('steps', wagtail.wagtailcore.fields.StreamField((('Schritt', wagtail.wagtailcore.blocks.TextBlock()),), blank=True, null=True, verbose_name='Vorbereitungsschritte')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Land')),
                ('year', models.IntegerField(choices=[(2017, 2017)], null=True, verbose_name='Jahr')),
                ('week', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53)], null=True, verbose_name='Woche')),
                ('dishes_sp', wagtail.wagtailcore.fields.StreamField((('menu', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.menu')),), blank=True, null=True, verbose_name='')),
                ('monday', wagtail.wagtailcore.fields.StreamField((('menu', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.menu')),), blank=True, null=True, verbose_name='')),
                ('tuesday', wagtail.wagtailcore.fields.StreamField((('menu', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.menu')),), blank=True, null=True, verbose_name='')),
                ('wednesday', wagtail.wagtailcore.fields.StreamField((('menu', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.menu')),), blank=True, null=True, verbose_name='')),
                ('thursday', wagtail.wagtailcore.fields.StreamField((('menu', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.menu')),), blank=True, null=True, verbose_name='')),
                ('friday', wagtail.wagtailcore.fields.StreamField((('menu', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.menu')),), blank=True, null=True, verbose_name='')),
            ],
        ),
    ]
