# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cultinadb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='steps',
            field=wagtail.wagtailcore.fields.StreamField((('Schritt', wagtail.wagtailcore.blocks.TextBlock()),), blank=True, null=True, verbose_name='Vorbereitungsschritte'),
        ),
    ]
