# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultinadb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture_url', models.URLField(blank=True)),
                ('type_of_ingrdients', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='M_Jahr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.CharField(help_text='2017, 2018, 2019, 2020...', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='M_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Mo, Di, Mi, Do, Fr, Sm', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='M_Woche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woche', models.CharField(help_text='01, 02, 03, 04, 05, 06...', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Menue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture_url', models.URLField(blank=True)),
                ('step_1', models.CharField(max_length=500)),
                ('step_2', models.CharField(max_length=500)),
                ('step_3', models.CharField(max_length=500)),
                ('step_4', models.CharField(max_length=500)),
                ('is_spicy', models.BooleanField(default=False, help_text='Ist diese Gericht Scharf?', verbose_name='Scharf')),
                ('is_vegi', models.BooleanField(default=False, help_text='Ist diese Gericht Vegi?', verbose_name='Vegi')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(help_text='Gericht, Suppe, Dessert', max_length=255, verbose_name='Art der Nahrung')),
            ],
        ),
        migrations.CreateModel(
            name='Wochen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cultinadb.M_Jahr')),
                ('menu_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_1', to='cultinadb.Menue')),
                ('menu_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_2', to='cultinadb.Menue')),
                ('menu_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_3', to='cultinadb.Menue')),
                ('menu_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_4', to='cultinadb.Menue')),
                ('tad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cultinadb.M_Tag')),
                ('tages_dessert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tages_dessert', to='cultinadb.Menue')),
                ('tages_suppe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tages_suppe', to='cultinadb.Menue')),
                ('woche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cultinadb.M_Woche')),
                ('wochen_spezialitaet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wochen_spezialitaet', to='cultinadb.Menue')),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='stream',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
        migrations.AddField(
            model_name='menue',
            name='type_of_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cultinadb.TypeOfDish'),
        ),
    ]
