# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cultinadb', '0002_auto_20170804_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='menue',
            name='zutaten',
            field=wagtail.wagtailcore.fields.StreamField((('zutaten', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.ingredients')),), blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='menue',
            name='is_spicy',
            field=models.BooleanField(default=False, verbose_name='Scharf'),
        ),
        migrations.AlterField(
            model_name='menue',
            name='is_vegi',
            field=models.BooleanField(default=False, verbose_name='Vegi'),
        ),
        migrations.AlterField(
            model_name='menue',
            name='picture_url',
            field=models.URLField(blank=True, verbose_name='Bild URL'),
        ),
        migrations.AlterField(
            model_name='menue',
            name='schritte_1',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='menue',
            name='schritte_2',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='menue',
            name='schritte_3',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='menue',
            name='schritte_4',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='menue',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='menue',
            name='type_of_dish_quantity',
            field=models.CharField(blank=True, choices=[('Gericht', 'Gericht'), ('Suppe', 'Suppe'), ('Dessert', 'Dessert'), ('...', '...')], default=False, max_length=2, verbose_name='Art der Nahrung'),
        ),
        migrations.AlterField(
            model_name='wochen',
            name='jahr_quantity',
            field=models.CharField(choices=[('2017', '2017')], max_length=2, null=True, verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='wochen',
            name='menu_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_1+', to='cultinadb.Menue'),
        ),
        migrations.AlterField(
            model_name='wochen',
            name='menu_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_2+', to='cultinadb.Menue'),
        ),
        migrations.AlterField(
            model_name='wochen',
            name='menu_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_3+', to='cultinadb.Menue'),
        ),
        migrations.AlterField(
            model_name='wochen',
            name='menu_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_4+', to='cultinadb.Menue'),
        ),
        migrations.AlterField(
            model_name='wochen',
            name='tag_quantity',
            field=models.CharField(choices=[('Mo', 'Mo'), ('Di', 'Di'), ('Mi', 'Mi'), ('Do', 'Do'), ('Fr', 'Fr')], max_length=2, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='wochen',
            name='tages_dessert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tages_dessert+', to='cultinadb.Menue', verbose_name='Tagesdessert'),
        ),
        migrations.AlterField(
            model_name='wochen',
            name='tages_suppe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tages_suppe+', to='cultinadb.Menue', verbose_name='Tagessuppe'),
        ),
        migrations.AlterField(
            model_name='wochen',
            name='woche_quantity',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53')], max_length=2, null=True, verbose_name='Woche'),
        ),
        migrations.AlterField(
            model_name='wochen',
            name='wochen_spezialitaet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wochen_spezialitaet+', to='cultinadb.Menue', verbose_name='Wochenspezialität'),
        ),
    ]
