# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 08:37
from __future__ import unicode_literals

import cultinadb.models
from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cultinadb', '0002_auto_20170821_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Ingredient',
            field=wagtail.wagtailcore.fields.StreamField((('zutaten', cultinadb.models.IngredientChooserBlock(target_model='cultinadb.ingredient')),), blank=True, null=True, verbose_name=''),
        ),
    ]
