# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultinadb', '0002_auto_20170725_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='type_of_ingrdients',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='translate_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='m_tag',
            name='tag',
            field=models.CharField(help_text='Mo, Di, Mi, Do, Fr, Sa', max_length=2),
        ),
    ]
