# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultinadb', '0003_auto_20170725_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wochen',
            old_name='tad',
            new_name='tag',
        ),
    ]
