# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 14:17
from __future__ import unicode_literals

import cultinadb.models
from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cultinadb', '0003_auto_20170824_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='dishes_sp',
            field=wagtail.wagtailcore.fields.StreamField((('menu', cultinadb.models.WeekChooserBlock(target_model='cultinadb.menu')),), blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='week',
            name='friday',
            field=wagtail.wagtailcore.fields.StreamField((('menu', cultinadb.models.WeekChooserBlock(target_model='cultinadb.menu')),), blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='week',
            name='monday',
            field=wagtail.wagtailcore.fields.StreamField((('menu', cultinadb.models.WeekChooserBlock(target_model='cultinadb.menu')),), blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='week',
            name='thursday',
            field=wagtail.wagtailcore.fields.StreamField((('menu', cultinadb.models.WeekChooserBlock(target_model='cultinadb.menu')),), blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='week',
            name='tuesday',
            field=wagtail.wagtailcore.fields.StreamField((('menu', cultinadb.models.WeekChooserBlock(target_model='cultinadb.menu')),), blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='week',
            name='wednesday',
            field=wagtail.wagtailcore.fields.StreamField((('menu', cultinadb.models.WeekChooserBlock(target_model='cultinadb.menu')),), blank=True, null=True, verbose_name=''),
        ),
    ]
