# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultinadb', '0004_auto_20170824_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Ingredient',
            new_name='ingredient',
        ),
    ]
