# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cultinadb', '0005_auto_20170805_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menue',
            name='is_spicy',
            field=models.BooleanField(default=False, verbose_name='Scharf'),
        ),
        migrations.AlterField(
            model_name='menue',
            name='is_vegi',
            field=models.BooleanField(default=False, verbose_name='Vegi'),
        ),
        migrations.AlterField(
            model_name='menue',
            name='zutaten',
            field=wagtail.wagtailcore.fields.StreamField((('zutaten', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='cultinadb.ingredients')),)),
        ),
    ]
