# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 19:23
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170308_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleindexpage',
            name='intro_de',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articleindexpage',
            name='intro_fr',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='intro_de',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='intro_fr',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default=''),
        ),
    ]
