# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_articlepage_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Frontpage'},
        ),
    ]
