# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170406_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='', max_length=40)),
                ('www', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
