# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170410_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='intro_de',
            new_name='intro',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='intro_fr',
            new_name='thanks',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='thanks_de',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='thanks_fr',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='title_fr',
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='on_homepage',
            field=models.BooleanField(default=False, help_text='Auf der Frontpage anzeigen', verbose_name='Featured'),
        ),
    ]
