# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
