# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_contactform_contactformfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Formular'},
        ),
    ]
