# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-21 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_articleindexpage_feed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
