# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_dataletssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')], default='twitter', max_length=16)),
                ('profile', models.CharField(default='', help_text='Name of the account, e.g. @myaccount', max_length=255)),
            ],
        ),
    ]
