# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_socialcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='analytics',
            field=models.CharField(blank=True, default='', help_text='Optional web analytics property code', max_length=60),
        ),
        migrations.AddField(
            model_name='contact',
            name='map_url',
            field=models.URLField(blank=True, help_text='Optional link of address to mapping provider', null=True),
        ),
        migrations.AlterField(
            model_name='socialcontact',
            name='profile',
            field=models.CharField(default='', help_text='Name of the account, e.g. @myaccount, or full URL', max_length=255),
        ),
    ]
