# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170510_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.ContactForm'),
        ),
    ]
